name: Recursive Submodule Zips and Push to Repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          submodules: false

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y zip git

      - name: Recursive zip and push
        run: |
          set -e
          ZIP_SIZE_LIMIT="2g"
          ZIP_FOLDER="Zipped-Code"
          REPO_ROOT=$(pwd)
          mkdir -p "$ZIP_FOLDER"

          zip_submodule() {
              local url="$1"
              local name="$2"
              local parent="$3"

              local out_folder="$parent/$name"
              mkdir -p "$ZIP_FOLDER/$out_folder"

              local zip_path="$REPO_ROOT/$ZIP_FOLDER/$out_folder/$name.zip"
              local log_path="$REPO_ROOT/$ZIP_FOLDER/$out_folder/$name.log"

              # Skip if zip already exists
              if [ -f "$zip_path" ]; then
                  echo "⏭ $zip_path exists, skipping."
                  return
              fi

              # Safe temp folder name
              local temp_dir="temp_clone_$(echo "$name" | tr '/' '_')"

              echo "📦 Cloning $url -> $name"
              git clone --depth 1 --recurse-submodules "$url" "$temp_dir"

              # Exclude nested submodules from current zip
              exclude=""
              for sm in $(find "$temp_dir" -maxdepth 1 -type d -name "*"); do
                  if [ -d "$sm/.git" ] && [ "$sm" != "$temp_dir" ]; then
                      exclude="$exclude --exclude=$(basename "$sm")/*"
                  fi
              done

              # Zip current module
              zip -r -s $ZIP_SIZE_LIMIT "$zip_path" "$temp_dir" $exclude > "$log_path" 2>&1 && \
                  echo "✅ Zipped $name" || echo "❌ Failed $name, see $log_path"

              # Commit & push
              git config user.name "github-actions"
              git config user.email "actions@github.com"
              git add "$ZIP_FOLDER/$out_folder/$name.zip" "$ZIP_FOLDER/$out_folder/$name.log"
              git commit -m "Add zip for $name" || echo "No changes to commit"
              git push origin main || echo "Push failed (possibly large file)"

              # Recurse into actual submodule directories
              for sm in $(find "$temp_dir" -maxdepth 1 -type d -name "*"); do
                  if [ -d "$sm/.git" ] && [ "$sm" != "$temp_dir" ]; then
                      sm_name=$(basename "$sm")
                      sm_url=$(git -C "$sm" config --get remote.origin.url)
                      zip_submodule "$sm_url" "$sm_name" "$out_folder"
                  fi
              done

              rm -rf "$temp_dir"
          }

          # --- Start from your fork ---
          MAIN_REPO_URL="https://github.com/UnrealCastLtd/esp-matter-zip.git"
          zip_submodule "$MAIN_REPO_URL" "esp-matter" "."
