name: Build ZIP

on:
  workflow_dispatch:   # allows you to trigger it manually from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main
          submodules: recursive

      - name: Create ZIP archive
        run: |
          zip -r esp-matter-main.zip . -x '*.git*'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: esp-matter-zip
          path: esp-matter-main.zip
