name: Zip Submodules Sequentially

on:
  workflow_dispatch:

jobs:
  zip_submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git and Checkout Main Repository
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0  # Fetch all history to ensure git submodule commands work correctly

      - name: Set up Git credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Install P7zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Create Zipped-Code directory
        run: mkdir -p Zipped-Code/

      - name: Recursively Find and Zip Submodules
        run: |
          # Use 'git submodule status --recursive' to get a list of all submodules
          # It provides the path and commit hash, which is more reliable than 'git foreach'
          git submodule status --recursive | while read -r line; do
            # Extract the submodule path from the output
            SUBMODULE_PATH=$(echo "$line" | awk '{print $2}')
            
            # The path for the zipped file and log will mirror the submodule's path
            SUBMODULE_ZIP_DIR="Zipped-Code/$(dirname "$SUBMODULE_PATH")"
            SUBMODULE_NAME=$(basename "$SUBMODULE_PATH")
            SUBMODULE_ZIP_NAME="$SUBMODULE_ZIP_DIR/$SUBMODULE_NAME.zip"
            SUBMODULE_LOG_NAME="$SUBMODULE_ZIP_DIR/$SUBMODULE_NAME.log"

            # Check if the zip file already exists in the repo
            if git ls-files --error-unmatch --Z "$SUBMODULE_ZIP_NAME" > /dev/null 2>&1; then
              echo "Skipping already existing zip for $SUBMODULE_PATH"
              continue
            fi
            
            echo "Processing submodule: $SUBMODULE_PATH"
            
            # Clone only the specific submodule
            git submodule update --init --recursive -- "$SUBMODULE_PATH"
            
            # Change into the submodule directory to perform the zip operation
            cd "$SUBMODULE_PATH"
            
            # Create the directory structure for the zip and log files if it doesn't exist
            mkdir -p "$GITHUB_WORKSPACE/$SUBMODULE_ZIP_DIR"
            
            # Use 7z to create a split archive (2GB chunks)
            7z a "$GITHUB_WORKSPACE/$SUBMODULE_ZIP_NAME" . -v2000m -r -x!*/.git* > "$GITHUB_WORKSPACE/$SUBMODULE_LOG_NAME" 2>&1

            # Go back to the root of the repo to commit and push
            cd "$GITHUB_WORKSPACE"
            
            # Commit and push the created zip and log files
            git add "$SUBMODULE_ZIP_NAME" "$SUBMODULE_LOG_NAME"
            git commit -m "Add zip and log for submodule: $SUBMODULE_PATH"
            git push

            # Clean up the temporary cloned submodule directory to save space
            rm -rf "$SUBMODULE_PATH"
          done
          
