name: Zip Submodules Sequentially

on:
  workflow_dispatch:

jobs:
  zip_submodules:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # Increased timeout for large repos

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4
        with:
          submodules: false # Do not clone submodules yet
          fetch-depth: 0 # Fetch all history to list all submodules

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Install P7zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Create Zipped-Code directory
        run: mkdir -p Zipped-Code/

      - name: Recursively Find, Clone, Zip, and Push Submodules
        run: |
          # Use 'git submodule status --recursive' to get a clean list of all submodule paths
          git submodule status --recursive | while read -r line; do
            SUBMODULE_PATH=$(echo "$line" | awk '{print $2}')
            SUBMODULE_ZIP_DIR="Zipped-Code/$(dirname "$SUBMODULE_PATH")"
            SUBMODULE_NAME=$(basename "$SUBMODULE_PATH")
            SUBMODULE_ZIP_NAME="$SUBMODULE_ZIP_DIR/$SUBMODULE_NAME.zip"
            SUBMODULE_LOG_NAME="$SUBMODULE_ZIP_DIR/$SUBMODULE_NAME.log"
            
            echo "::group::Processing $SUBMODULE_PATH"
            
            # Check if the zip file already exists in the main repo to skip re-zipping.
            if git ls-files --error-unmatch --Z "$SUBMODULE_ZIP_NAME" > /dev/null 2>&1; then
              echo "Skipping already existing zip for $SUBMODULE_PATH"
              echo "::endgroup::"
              continue
            fi
            
            echo "Cloning submodule: $SUBMODULE_PATH"
            
            # Clone only the specific submodule, but not its submodules.
            git submodule update --init -- "$SUBMODULE_PATH"

            # Check for nested submodules and clone them individually within the same loop.
            if [ -f "$SUBMODULE_PATH/.gitmodules" ]; then
              echo "Handling nested submodules within $SUBMODULE_PATH"
              cd "$SUBMODULE_PATH"
              git submodule status --recursive | while read -r nested_line; do
                NESTED_PATH=$(echo "$nested_line" | awk '{print $2}')
                git submodule update --init --recursive -- "$NESTED_PATH"
              done
              cd "$GITHUB_WORKSPACE"
            fi
            
            # Change into the submodule's directory to perform the zipping.
            cd "$SUBMODULE_PATH"
            
            echo "Zipping and creating log for $SUBMODULE_PATH"
            
            # Create the directory structure for the zip and log files if it doesn't exist.
            mkdir -p "$GITHUB_WORKSPACE/$SUBMODULE_ZIP_DIR"
            
            # Zip the submodule's content, preserving the folder structure inside the zip.
            7z a "$GITHUB_WORKSPACE/$SUBMODULE_ZIP_NAME" . -v2000m -r -x!*/.git* > "$GITHUB_WORKSPACE/$SUBMODULE_LOG_NAME" 2>&1
            
            # Move back to the main repository's root to commit and push.
            cd "$GITHUB_WORKSPACE"
            
            echo "Committing and pushing files for $SUBMODULE_PATH"
            git add "$SUBMODULE_ZIP_NAME" "$SUBMODULE_LOG_NAME"
            git commit -m "Add zip and log for submodule: $SUBMODULE_PATH"
            git push
            
            echo "Cleaning up local files for $SUBMODULE_PATH"
            
            # Delete the temporary cloned submodule to free up disk space.
            rm -rf "$SUBMODULE_PATH"
            
            echo "::endgroup::"
          done
          
