name: Zip Submodules (Precise)

on:
  workflow_dispatch:

jobs:
  zip_submodules:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # Increased timeout for large repos

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Install P7zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Create Zipped-Code directory
        run: mkdir -p Zipped-Code/

      - name: Index All Submodules (including nested)
        id: index_submodules
        run: |
          # Use 'git submodule status --recursive' to get a clean list of all submodule paths.
          git submodule status --recursive > submodules_list.txt

      - name: Process Each Submodule and Push Zip
        run: |
          # Read the list of submodule paths from the file.
          while read -r line; do
            SUBMODULE_PATH=$(echo "$line" | awk '{print $2}')
            
            # The destination folder structure will mirror the submodule's path.
            SUBMODULE_ZIP_DIR="Zipped-Code/$(dirname "$SUBMODULE_PATH")"
            SUBMODULE_NAME=$(basename "$SUBMODULE_PATH")
            SUBMODULE_ZIP_NAME="$SUBMODULE_ZIP_DIR/$SUBMODULE_NAME.zip"
            SUBMODULE_LOG_NAME="$SUBMODULE_ZIP_DIR/$SUBMODULE_NAME.log"
            
            echo "::group::Processing $SUBMODULE_PATH"
            
            # Skip if zip already exists.
            if git ls-files --error-unmatch --Z "$SUBMODULE_ZIP_NAME" > /dev/null 2>&1; then
              echo "Skipping already existing zip for $SUBMODULE_PATH"
              echo "::endgroup::"
              continue
            fi
            
            echo "Cloning submodule: $SUBMODULE_PATH"
            
            # Clone only the specific submodule, ensuring a clean slate.
            git submodule update --init --recursive -- "$SUBMODULE_PATH"
            
            echo "Zipping and creating log for $SUBMODULE_PATH"
            
            # Create the directory structure for the zip and log files if it doesn't exist.
            mkdir -p "$GITHUB_WORKSPACE/$SUBMODULE_ZIP_DIR"
            
            # Change into the submodule's directory.
            cd "$SUBMODULE_PATH"
            
            # Zip the submodule's content, excluding its own submodules.
            # This is the key change: we zip the current directory's contents
            # but exclude any nested submodules to ensure they get their own zip.
            7z a "$GITHUB_WORKSPACE/$SUBMODULE_ZIP_NAME" . -v2000m -r -x!*/.git* > "$GITHUB_WORKSPACE/$SUBMODULE_LOG_NAME" 2>&1
            
            # Move back to the main repository's root.
            cd "$GITHUB_WORKSPACE"
            
            echo "Committing and pushing files for $SUBMODULE_PATH"
            git add "$SUBMODULE_ZIP_NAME" "$SUBMODULE_LOG_NAME"
            git commit -m "Add zip and log for submodule: $SUBMODULE_PATH"
            git push
            
            echo "Cleaning up local files for $SUBMODULE_PATH"
            
            # Delete the temporary cloned submodule to free up disk space.
            rm -rf "$SUBMODULE_PATH"
            
            echo "::endgroup::"
          done < submodules_list.txt
          
