name: Build Zips Per Submodule

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main
          submodules: recursive

      - name: Remove .git folders to save space
        run: |
          find . -name ".git" -type d -prune -exec rm -rf {} +

      - name: Create zips for each submodule
        run: |
          mkdir submodule_zips
          while read path; do
            name=$(basename "$path")
            echo "📦 Zipping submodule: $name ($path)"
            if zip -r "submodule_zips/${name}.zip" "$path" > "submodule_zips/${name}.log" 2>&1; then
              echo "✅ Successfully zipped $name"
            else
              echo "❌ Failed to zip $name, check submodule_zips/${name}.log"
            fi
          done < <(git config --file .gitmodules --get-regexp path | awk '{print $2}')

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp-matter-submodules
          path: submodule_zips
